#!/usr/bin/env bash
#
# Common installation on all nodes
#
############################################

# Determine script home full path
SCRIPT_HOME=/vagrant

# Load library
source $SCRIPT_HOME/.library || {
  echo "ERROR: Failed to load the library script $SCRIPT_HOME/.library"
  exit 3
}


############################################
# Install kubernetes pre-requisites
############################################
cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
exclude=kubelet kubeadm kubectl
EOF

yum install -y --disableexcludes=kubernetes \
  kubelet-${KUBERNETES_VERSION} \
  kubectl-${KUBERNETES_VERSION} \
  kubeadm-${KUBERNETES_VERSION}

systemctl start kubelet
systemctl enable kubelet
