apiVersion: v1
kind: Namespace
metadata:
  name: security
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trivy
  name: trivy
  namespace: security
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivy
  template:
    metadata:
      labels:
        app: trivy
    spec:
      containers:
      - image: aquasec/trivy
        name: trivy
        args:
        - server
        ports:
        - containerPort: 4954
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: trivy
  name: trivy
  namespace: security
spec:
  ports:
  - port: 4954
    protocol: TCP
    targetPort: 4954
  selector:
    app: trivy

