#!/usr/bin/env bash
#
# Setup NFS dynamic volume provisioning
#
# Example PVC manifest
#
#  kind: PersistentVolumeClaim
#  apiVersion: v1
#  metadata:
#    name: my-claim
#    annotations:
#      # Check the variable NFS_STORAGE_CLASS see the value
#      volume.beta.kubernetes.io/storage-class: "nfs-storage"
#  spec:
#    accessModes:
#      - ReadWriteOnce
#    resources:
#      requests:
#        storage: 1Mi
#
############################################

# Determine script home full path
SCRIPT_HOME=/vagrant/scripts

# Load library
source $SCRIPT_HOME/.library || {
  echo "ERROR: Failed to load the library script $SCRIPT_HOME/.library"
  exit 3
}

############################################
# Install using inline manifests
############################################

TEMP_DIR=$(mktemp -d)
log "Work directory $TEMP_DIR"

# envsubst requires variables exported
# 20230517: This may no longer needed
export ADMIN_VM_IP NFS_FOLDER NFS_STORAGE_CLASS

# Install NFS provisioner
helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/ || \
  error "Failed to add helm repository"

valueFile=$(mktemp)
cat <<EOF > $valueFile
nfs:
  server: ${ADMIN_VM_IP}
  path: ${NFS_FOLDER}

storageClass:
  name: ${NFS_STORAGE_CLASS}
  create: true
  defaultClass: true

# Allow running on master
tolerations:
- effect: NoSchedule
  key: node-role.kubernetes.io/master
  operator: Exists
EOF

helm install nfs-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner \
    --values $valueFile || error "Failed to install the nfs-provisioner"

rm -f $valueFile

# Cleanup
rm -rf $TEMP_DIR
