#!/usr/bin/env bash
#
# Install NFS server
#
############################################

# Determine script home full path
SCRIPT_HOME=/vagrant/scripts

# Load library
source $SCRIPT_HOME/.library || {
  echo "ERROR: Failed to load the library script $SCRIPT_HOME/.library"
  exit 3
}

############################################
# Install and configure NFS server
############################################
apt install -y nfs-kernel-server

systemctl start nfs-kernel-server
systemctl enable nfs-kernel-server

mkdir -p $NFS_FOLDER
chmod 755 $NFS_FOLDER

cat<<EOF >/etc/exports
/nfs  172.24.20.0/24(rw,all_squash,sync,no_root_squash,no_subtree_check)
EOF

exportfs -a
