#!/usr/bin/env bash
#
# Common installation on all nodes
#
# References: 
# https://www.linuxtechi.com/install-kubernetes-on-ubuntu-22-04/
#
############################################

# Determine script home full path
SCRIPT_HOME=/vagrant/scripts

# Load library
source $SCRIPT_HOME/.library || {
  echo "ERROR: Failed to load the library script $SCRIPT_HOME/.library"
  exit 3
}

############################################
# OS Pre-requisites
############################################
# Disable firewall and apparmor as this is learning environment

# Disable swap
swapoff -a
sed -i 's|^/swap|# /swap|g' /etc/fstab

# Disable firewall
ufw disable

# Update containerd configuration
tee /etc/modules-load.d/containerd.conf <<EOF
overlay
br_netfilter
EOF
modprobe overlay
modprobe br_netfilter

# Letting iptables see bridge traffic
cat<<EOF > /etc/sysctl.d/10-k8s.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_forward = 1
EOF
sysctl --system

# Stop apparmor
systemctl stop apparmor
systemctl disable apparmor

# Install docker
apt update || error "Ubuntu update failed"
apt install -y docker.io || error "Docker installation failed"

# Add kuberenetes sources
# echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list

############################################
# Install containerd
############################################
# Install packages
apt install -y curl gnupg2 software-properties-common apt-transport-https ca-certificates
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmour -o /etc/apt/trusted.gpg.d/docker.gpg
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
apt update
apt install -y containerd.io

containerd config default | sudo tee /etc/containerd/config.toml >/dev/null 2>&1
sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml

systemctl restart containerd
systemctl enable containerd

log "Complete base installation"
