#!/usr/bin/env bash
#
# Common installation on all nodes
#
############################################

# Determine script home full path
SCRIPT_HOME=/vagrant/scripts

# Load library
source $SCRIPT_HOME/.library || {
  echo "ERROR: Failed to load the library script $SCRIPT_HOME/.library"
  exit 3
}

############################################
# Mount NFS share
############################################
mkdir -p $NFS_MOUNT
yum install -y nfs-utils

# Check whether entry already added. If not add the entry.
grep -q "^$ADMIN_VM_IP:$NFS_FOLDER" /etc/fstab || echo "$ADMIN_VM_IP:$NFS_FOLDER      $NFS_MOUNT     nfs     defaults   0 0" >> /etc/fstab
mount -a

############################################
# Initialize cluster
############################################

KUBEADM_CONFIG=$(mktemp)
NODE_IP=$(ip address show dev ${VM_CLUSTER_NIC_ID} scope global | grep inet | sed 's/.*inet\s*\([0-9]*\.[0-9]*\.[0-9]*\.[0-9]*\).*/\1/g')

cat <<EOF > $KUBEADM_CONFIG
---
kind: JoinConfiguration
apiVersion: kubeadm.k8s.io/v1beta2
discovery:
  bootstrapToken:
    apiServerEndpoint: "${MASTER_NODE_IP}:${API_SERVER_PORT}"
    token: ${BOOTSTRAP_TOKEN}
    unsafeSkipCAVerification: true
  timeout: 5m0s
nodeRegistration:
  kubeletExtraArgs:
    node-ip: ${NODE_IP}
certificateKey: "${CERTIFICATE_KEY}"
EOF

# Check kubelet service is running. If running it is assumed node has been already joined to the cluster
systemctl status kubelet >/dev/null >&1 || kubeadm join --config $KUBEADM_CONFIG

