#!/usr/bin/env bash
#
# Common installation on all nodes
#
############################################

# Determine script home full path
SCRIPT_HOME=/vagrant/scripts

# Load library
source $SCRIPT_HOME/.library || {
  echo "ERROR: Failed to load the library script $SCRIPT_HOME/.library"
  exit 3
}

############################################
# Join cluster
############################################

KUBEADM_CONFIG=$(mktemp)
NODE_IP=$(ip address show dev enp0s8 scope global | grep inet | sed 's/.*inet\s*\([0-9]*\.[0-9]*\.[0-9]*\.[0-9]*\).*/\1/g')

cat <<EOF > $KUBEADM_CONFIG
---
kind: JoinConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
discovery:
  bootstrapToken:
    apiServerEndpoint: "${MASTER_NODE_IP}:${API_SERVER_PORT}"
    token: ${BOOTSTRAP_TOKEN}
    unsafeSkipCAVerification: true
  timeout: 5m0s
nodeRegistration:
  kubeletExtraArgs:
    node-ip: ${NODE_IP}
EOF

# Check kubelet service is running. If running it is assumed node has been already joined to the cluster
systemctl status kubelet >/dev/null >&1 || kubeadm join --config $KUBEADM_CONFIG
